export const PACKAGE_EXCLUDE_ENTRIES = [
  ".git/*",
  ".github/*",
  ".playwright-mcp/*",
  "build.gradle",
  "eslint.config.mjs",
  "gradle/*",
  "gradlew",
  "gradlew.bat",
  "node_modules/*",
  "package.json",
  "pnpm-lock.yaml",
  "src/*",
  "scripts/*",
  "settings.gradle",
  "tailwind.config.js",
  "tsconfig.json",
  "vite.config.ts",
];

export const PACKAGE_FORBIDDEN_PATTERNS = [
  /^pnpm-lock\.yaml$/,
  /^package\.json$/,
  /^scripts\//,
  /^node_modules\//,
  /^\.git\//,
  /^build\.gradle$/,
  /^settings\.gradle$/,
  /^gradlew(?:\.bat)?$/,
  /^gradle\//,
  /^\.playwright-mcp\//,
  /^src\//,
  /^\.github\//,
  /^eslint\.config/,
  /^vite\.config/,
  /^tailwind\.config/,
  /^tsconfig\.json$/,
];
